### ISSUE TITLE
FlowControl check can overflow/underflow

### ISSUE THREAD

**Issue by vervaekejonathan** [xythobuz/avrSerial#3]
https://github.com/xythobuz/avrSerial/blob/master/serial.c#L224
https://github.com/xythobuz/avrSerial/blob/master/serial.c#L337

When rxBufferElements[uart] is zero, it underflows and the flowcontrol is triggered when it shouldn't
When this happens, the flowcontrol will trigger often, because rxBufferElements[uart] switches between 0xFF and 0x00

Also, an RX_BUFFER_SIZE of > 0xFF will cause unwanted flowcontrol messages. I suggest compile time check here.

**Comment by xythobuz** [comment]
Thanks for spotting and reporting these problems!

The flow control code should now be usable with buffers up to 64KB in size. The underflow issue should now also be resolved.

While I was at it, I also 'fixed' a bug where the receive buffer would get completely corrupted when it overflows from receiving another byte. It will now just overwrite the last byte received over and over again.

I haven't really tested these changes, so feedback is definitely welcome! 😃
